# Generated by Django 3.1.1 on 2020-10-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgemediastore',
            name='m_k_id',
        ),
    ]
