# Generated by Django 3.1.1 on 2020-09-11 01:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=20)),
                ('w_type', models.CharField(max_length=20)),
                ('w_content', models.CharField(max_length=2000)),
                ('w_status', models.CharField(choices=[(1, '未处理'), (2, '已处理')], max_length=10)),
                ('w_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='devicemaintainrecord',
            name='dm_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Worksheetmedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wm_w_filepath', models.ImageField(upload_to='wmedia/%Y%m%d')),
                ('wm_date', models.DateTimeField()),
                ('wm_w_id', models.ForeignKey(db_column='wm_w_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='One.worksheet')),
            ],
        ),
    ]
