# Generated by Django 3.1.1 on 2020-09-11 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0002_auto_20200911_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemaintainrecord',
            name='dm_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 11, 9, 47, 31, 548834)),
        ),
    ]
