# Generated by Django 3.1.1 on 2020-10-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0002_remove_knowledgemediastore_m_k_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
