# Generated by Django 3.1.1 on 2020-09-11 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0004_auto_20200911_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='d_c_id',
        ),
        migrations.AlterField(
            model_name='devicemaintainrecord',
            name='dm_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32)),
                ('p_description', models.CharField(max_length=300)),
                ('p_type', models.CharField(max_length=20)),
                ('p_customer_type', models.CharField(max_length=20)),
                ('p_partya', models.CharField(max_length=30)),
                ('p_purchase_time', models.DateTimeField()),
                ('p_setup_time', models.DateTimeField()),
                ('p_built_time', models.DateTimeField()),
                ('p_contact_name', models.CharField(max_length=20)),
                ('p_contact_number', models.IntegerField()),
                ('p_province', models.CharField(max_length=10)),
                ('p_city', models.CharField(max_length=10)),
                ('p_address', models.CharField(max_length=100)),
                ('p_longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('p_latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('p_c_id', models.ForeignKey(db_column='p_c_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='One.company')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='d_p_id',
            field=models.ForeignKey(db_column='d_p_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='One.project'),
        ),
    ]
