# Generated by Django 3.1.1 on 2020-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0004_knowledge_k_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_status',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
