# Generated by Django 3.1.1 on 2020-10-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0005_auto_20201010_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_status',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
