# Generated by Django 3.1.1 on 2020-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0005_auto_20200911_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='u_company_id',
            field=models.IntegerField(null=True),
        ),
    ]
