# Generated by Django 3.1.1 on 2020-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0006_auto_20201010_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_status',
            field=models.BooleanField(default=0),
        ),
    ]
