# Generated by Django 3.1.1 on 2020-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0006_auto_20200911_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=128),
        ),
    ]
