# Generated by Django 3.1.1 on 2020-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0007_auto_20200914_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
