# Generated by Django 3.1.2 on 2020-10-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0007_auto_20201010_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectdevice',
            name='cd_c_id',
            field=models.ForeignKey(db_column='cd_c_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='One.company'),
        ),
    ]
