# Generated by Django 3.1.2 on 2020-10-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0008_collectdevice_cd_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemaintainrecord',
            name='dm_o_name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
