# Generated by Django 3.1.1 on 2020-09-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0008_auto_20200914_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='d_datastatus',
            new_name='d_data_status',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='d_lastcontracttime',
            new_name='d_last_contract_time',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='d_registertime',
            new_name='d_register_time',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='d_seriesnumber',
            new_name='d_series_number',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='p_partya',
            new_name='p_party_a',
        ),
    ]
