# Generated by Django 3.1.2 on 2020-10-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0009_devicemaintainrecord_dm_o_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemaintainrecord',
            name='dm_o_name',
        ),
    ]
