# Generated by Django 3.1.1 on 2020-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0009_auto_20200914_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
