# Generated by Django 3.1.1 on 2020-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0010_auto_20200915_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
