# Generated by Django 3.1.1 on 2020-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0011_auto_20200915_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='context',
            field=models.CharField(default='略', max_length=128, null=True),
        ),
    ]
