# Generated by Django 3.1.1 on 2020-09-16 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0012_auto_20200915_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_u_id',
            field=models.ForeignKey(db_column='p_u_id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
