# Generated by Django 3.1.1 on 2020-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0013_project_p_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='d_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='p_active',
            field=models.IntegerField(default=0),
        ),
    ]
