# Generated by Django 3.1.2 on 2020-10-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0013_knowledgemediastore_m_k_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='tag',
            new_name='k_tag',
        ),
    ]
