# Generated by Django 3.1.1 on 2020-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0014_auto_20200916_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemaintainrecord',
            name='dm_time',
            field=models.DateTimeField(),
        ),
    ]
