# Generated by Django 3.1.2 on 2020-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0014_auto_20201013_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
