# Generated by Django 3.1.2 on 2020-10-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0015_auto_20201013_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_tag',
            field=models.CharField(blank=True, default='无', max_length=20),
        ),
    ]
