# Generated by Django 3.1.1 on 2020-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0015_auto_20200916_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_active',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
