# Generated by Django 3.1.1 on 2020-09-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0016_auto_20200917_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_c_id',
            field=models.ForeignKey(db_column='p_c_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.company'),
        ),
    ]
