# Generated by Django 3.1.2 on 2020-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0016_auto_20201013_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '客服聊天记录', 'verbose_name_plural': '客服聊天记录'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='unread',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='聊天信息'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='chat_records',
        ),
    ]
