# Generated by Django 3.1.1 on 2020-09-18 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0017_auto_20200917_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='context',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_m_id',
            field=models.ForeignKey(db_column='d_mm_id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
