# Generated by Django 3.1.2 on 2020-10-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0017_auto_20201013_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='is_employee',
            field=models.BooleanField(default=0),
        ),
    ]
