# Generated by Django 3.1.1 on 2020-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0018_auto_20200918_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='d_u_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
