# Generated by Django 3.1.2 on 2020-10-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0018_loginuser_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=64),
        ),
    ]
