# Generated by Django 3.1.2 on 2020-10-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0019_auto_20201014_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='p_latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='p_longitude',
        ),
    ]
