# Generated by Django 3.1.1 on 2020-09-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0019_device_d_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='a_high_level',
            field=models.CharField(choices=[(1, '正常'), (2, '提醒'), (3, '告警')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_high_line',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_high_tip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_highest_level',
            field=models.CharField(choices=[(1, '正常'), (2, '提醒'), (3, '告警')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_highest_line',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_highest_tip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_low_level',
            field=models.CharField(choices=[(1, '正常'), (2, '提醒'), (3, '告警')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_low_tip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_lowest_level',
            field=models.CharField(choices=[(1, '正常'), (2, '提醒'), (3, '告警')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_lowest_line',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_lowest_tip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
