# Generated by Django 3.1.2 on 2020-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0020_auto_20201015_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_built_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_purchase_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_setup_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
