# Generated by Django 3.1.2 on 2020-10-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0021_auto_20201015_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_register_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_active',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
