# Generated by Django 3.1.1 on 2020-09-21 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0021_auto_20200921_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainrecord',
            name='cr_e_id',
            field=models.ForeignKey(blank=True, db_column='cr_e_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
