# Generated by Django 3.1.1 on 2020-09-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0022_auto_20200921_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='a_high_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_highest_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_low_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_lowest_level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cm_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complainrecord',
            name='cr_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_data_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='k_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledgemediastore',
            name='m_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='u_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='s_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='w_status',
            field=models.CharField(max_length=10),
        ),
    ]
