# Generated by Django 3.1.1 on 2020-09-25 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0023_auto_20200923_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheetmedia',
            old_name='wm_w_filepath',
            new_name='wm_w_image',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='w_e_id',
            field=models.ForeignKey(db_column='w_e_id', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
