# Generated by Django 3.1.2 on 2020-10-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0023_collectdevice_cd_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_user_id', models.IntegerField()),
                ('e_user_name', models.CharField(default=0, max_length=32)),
                ('e_title', models.CharField(max_length=32)),
                ('e_image', models.ImageField(upload_to='emedia/%Y%m%d')),
                ('e_date', models.DateTimeField()),
                ('e_content', models.CharField(max_length=20000)),
            ],
        ),
    ]
