# Generated by Django 3.1.2 on 2020-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0024_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='e_image',
            field=models.FileField(upload_to='emedia/%Y%m%d'),
        ),
    ]
