# Generated by Django 3.1.2 on 2020-10-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0025_auto_20201027_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_icon',
            field=models.FileField(upload_to='cicons/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='knowledgemediastore',
            name='m_k_filepath',
            field=models.FileField(upload_to='kmedia/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='u_icon',
            field=models.FileField(null=True, upload_to='uicons/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='test',
            name='t',
            field=models.FileField(upload_to='tmedia/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='worksheetmedia',
            name='wm_w_image',
            field=models.FileField(upload_to='wmedia/%Y%m%d'),
        ),
    ]
