# Generated by Django 3.1.2 on 2020-10-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0026_auto_20201027_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='e_content',
            field=models.TextField(),
        ),
    ]
