# Generated by Django 3.1.2 on 2020-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0027_auto_20201028_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cd_dashboard',
            field=models.TextField(null=True),
        ),
    ]
