# Generated by Django 3.1.2 on 2020-10-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0028_project_cd_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cd_dashboard',
            new_name='p_dashboard',
        ),
    ]
