# Generated by Django 3.1.2 on 2020-10-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0029_auto_20201029_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectdevice',
            old_name='cd_tunnel',
            new_name='cd_nodeid',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_active',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_dashboard',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_data_status',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_last_contract_time',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_name',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_register_time',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_series_number',
        ),
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_status',
        ),
    ]
