# Generated by Django 3.1.2 on 2020-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0030_auto_20201029_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='wisepasstoken',
            field=models.TextField(null=True),
        ),
    ]
