# Generated by Django 3.1.2 on 2020-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0031_loginuser_wisepasstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WisePassToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(null=True)),
            ],
        ),
    ]
