# Generated by Django 3.1.2 on 2020-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0032_wisepasstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectdevice',
            name='cd_manufacturer',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_produce_time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
