# Generated by Django 3.1.2 on 2020-11-03 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0033_auto_20201102_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='collectdevice',
            field=models.ManyToManyField(to='One.Collectdevice'),
        ),
        migrations.AlterField(
            model_name='collectdevice',
            name='cd_m_id',
            field=models.ForeignKey(db_column='cd_m_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='capply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='u_type',
            field=models.CharField(default='游客', max_length=10),
        ),
    ]
