# Generated by Django 3.1.2 on 2021-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0034_auto_20201103_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='knowledge',
            field=models.ManyToManyField(to='One.Knowledge'),
        ),
    ]
