# Generated by Django 3.1.2 on 2021-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0035_loginuser_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='k_thumbs_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='k_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='k_tag',
            field=models.CharField(blank=True, default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
