# Generated by Django 3.1.2 on 2021-01-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0036_auto_20210107_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu_user_id', models.IntegerField()),
                ('thu_k_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='One.knowledge')),
            ],
        ),
    ]
