# Generated by Django 3.1.2 on 2021-01-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0037_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='u_department',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
