# Generated by Django 3.1.2 on 2021-01-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0038_loginuser_u_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='u_department',
        ),
    ]
