# Generated by Django 3.1.2 on 2021-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0039_remove_loginuser_u_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='k_tag',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='tag',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='k_tag',
            field=models.ManyToManyField(to='One.Tag'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='tag',
            field=models.ManyToManyField(to='One.Tag'),
        ),
    ]
