# Generated by Django 3.1.2 on 2021-01-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0040_auto_20210108_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='tech/%Y%m%d')),
            ],
        ),
    ]
