# Generated by Django 3.1.2 on 2021-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0041_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_f_ip',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
