# Generated by Django 3.1.2 on 2021-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0042_doc_doc_f_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc',
            name='doc_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
