# Generated by Django 3.1.2 on 2021-01-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0044_auto_20210111_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='w_id',
            field=models.IntegerField(null=True),
        ),
    ]
