# Generated by Django 3.1.2 on 2021-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0045_doc_w_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='w_wechat',
            field=models.BooleanField(default=True),
        ),
    ]
