# Generated by Django 3.1.2 on 2021-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0046_worksheet_w_wechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='w_doc_id',
            field=models.IntegerField(default=None),
        ),
    ]
