# Generated by Django 3.1.2 on 2021-01-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0047_worksheet_w_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='w_u_phone',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
