# Generated by Django 3.1.2 on 2021-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0050_auto_20210112_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_register_number',
            field=models.BigIntegerField(null=True, verbose_name='营业执照注册号'),
        ),
    ]
