# Generated by Django 3.1.2 on 2021-01-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0051_auto_20210112_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=110, null=True, unique=True, verbose_name='企业地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_business_range',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='经营范围'),
        ),
    ]
