# Generated by Django 3.1.2 on 2021-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0052_auto_20210112_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_business_range',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='经营范围'),
        ),
    ]
