# Generated by Django 3.1.2 on 2021-01-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0053_auto_20210112_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='k_tag',
            new_name='tag',
        ),
    ]
