# Generated by Django 3.1.2 on 2021-01-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0054_auto_20210113_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_user_id',
            field=models.CharField(max_length=32),
        ),
    ]
