# Generated by Django 3.1.2 on 2021-01-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0055_auto_20210113_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='ddd_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='p_city',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='ddd_detail',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='公司激活状态'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_c_id',
            field=models.ForeignKey(db_column='d_c_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.collectdevice'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_m_id',
            field=models.ForeignKey(db_column='d_mm_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_p_id',
            field=models.ForeignKey(db_column='d_p_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.project'),
        ),
    ]
