# Generated by Django 3.1.2 on 2021-01-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0056_auto_20210119_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectdevice',
            name='cd_nodeid',
        ),
    ]
