# Generated by Django 3.1.2 on 2021-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0057_remove_collectdevice_cd_nodeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectdevice',
            name='cd_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_device_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_port_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_primary_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_primary_ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_primary_port',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_secondary_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_secondary_ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_secondary_port',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_unit_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
