# Generated by Django 3.1.2 on 2021-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0060_auto_20210119_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
