# Generated by Django 3.1.2 on 2021-01-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0061_auto_20210120_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='p_province',
            new_name='p_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_organize_code',
        ),
        migrations.AddField(
            model_name='knowledge',
            name='k_checker',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='k_condition',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='k_v_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='k_verify',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='work',
            field=models.CharField(max_length=10, null=True, verbose_name='职务'),
        ),
        migrations.AddField(
            model_name='project',
            name='p_c_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='p_position',
            field=models.CharField(max_length=40, null=True, verbose_name='经纬度'),
        ),
    ]
