# Generated by Django 3.1.2 on 2021-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0063_data_d_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d_alarm',
            field=models.BooleanField(default=False),
        ),
    ]
