# Generated by Django 3.1.2 on 2021-01-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0064_data_d_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('f_subject', models.CharField(max_length=20)),
                ('f_number', models.IntegerField()),
                ('f_machine', models.IntegerField()),
                ('f_else', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
