# Generated by Django 3.1.2 on 2021-01-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0069_auto_20210127_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fittings',
            new_name='Fitting',
        ),
    ]
