# Generated by Django 3.1.2 on 2021-01-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0071_auto_20210127_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fittings',
        ),
    ]
