# Generated by Django 3.1.2 on 2021-01-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0072_delete_fittings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fittings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('f_number', models.CharField(max_length=20, null=True)),
                ('f_machine', models.CharField(max_length=20, null=True)),
                ('f_else', models.TextField(blank=True, null=True)),
                ('f_image', models.ImageField(null=True, upload_to='fittings_image/%Y%m%d', verbose_name='配件设备图片')),
                ('f_subject', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='One.fitsub')),
            ],
        ),
    ]
