# Generated by Django 3.1.2 on 2021-01-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0073_fittings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectdevice',
            name='cd_GPS',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_SIM',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_SN',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_data_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_install_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_last_contract_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collectdevice',
            name='cd_placed',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
