# Generated by Django 3.1.2 on 2021-01-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0074_auto_20210127_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='d_data_status',
        ),
        migrations.RemoveField(
            model_name='device',
            name='d_last_contract_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='d_series_number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='d_tunnel',
        ),
        migrations.AddField(
            model_name='device',
            name='d_GPS',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='d_manufacturer',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='d_produce_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_register_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
