# Generated by Django 3.1.2 on 2021-01-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0075_auto_20210127_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d_cd_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectdevice',
            name='cd_c_id',
            field=models.ForeignKey(db_column='cd_c_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.company'),
        ),
        migrations.AlterField(
            model_name='collectdevice',
            name='cd_p_id',
            field=models.ForeignKey(db_column='cd_p_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.project'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_d_id',
            field=models.ForeignKey(db_column='d_d_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.device'),
        ),
    ]
