# Generated by Django 3.1.2 on 2021-01-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0077_auto_20210127_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_d_id',
            field=models.ForeignKey(db_column='d_d_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='One.device'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_g_id',
            field=models.ForeignKey(db_column='d_g_id', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='One.datagroup'),
        ),
    ]
