# Generated by Django 3.1.2 on 2021-01-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0078_auto_20210128_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_g_id',
            field=models.ForeignKey(blank=True, db_column='d_g_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='One.datagroup'),
        ),
        migrations.AlterField(
            model_name='device',
            name='d_active',
            field=models.IntegerField(default=1),
        ),
    ]
