# Generated by Django 3.1.2 on 2021-01-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0080_auto_20210129_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='d_co_id',
            field=models.ForeignKey(db_column='d_co_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.company'),
        ),
    ]
