# Generated by Django 3.1.2 on 2021-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0081_device_d_co_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='realtimevalue',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
