# Generated by Django 3.1.2 on 2021-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0082_datagroup_realtimevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='has_data',
            field=models.BooleanField(default=0),
        ),
    ]
