# Generated by Django 3.1.2 on 2021-01-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0083_datagroup_has_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='a_data_id',
        ),
        migrations.AddField(
            model_name='alert',
            name='a_datagroup_id',
            field=models.ForeignKey(db_column='a_datagroup_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='One.datagroup'),
        ),
    ]
