# Generated by Django 3.1.2 on 2021-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0084_auto_20210129_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='has_alert',
            field=models.BooleanField(default=0),
        ),
    ]
