# Generated by Django 3.1.2 on 2021-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0085_datagroup_has_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemaintainrecord',
            name='dm_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
