# Generated by Django 3.1.2 on 2021-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0086_devicemaintainrecord_dm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemaintainrecord',
            name='dm_d_detail',
            field=models.TextField(),
        ),
    ]
