# Generated by Django 3.1.2 on 2021-02-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0087_auto_20210201_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_value', models.CharField(max_length=50, null=True)),
                ('dl_time', models.DateTimeField(null=True)),
                ('dl_g_id', models.ForeignKey(db_column='dl_g_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.datagroup')),
            ],
        ),
    ]
