# Generated by Django 3.1.2 on 2021-02-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0088_datalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='realtime',
            field=models.DateTimeField(null=True),
        ),
    ]
