# Generated by Django 3.1.2 on 2021-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0089_datagroup_realtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='d_alert_count',
            field=models.IntegerField(default=0),
        ),
    ]
