# Generated by Django 3.1.2 on 2021-02-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0090_device_d_alert_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=100, null=True)),
                ('log_alarm_type', models.CharField(max_length=20, null=True)),
                ('log_alarm_data', models.CharField(max_length=10, null=True)),
                ('log_group_name', models.CharField(max_length=20, null=True)),
                ('log_message', models.CharField(default='设备数值超出告警值', max_length=50)),
                ('log_type', models.CharField(default='未解决', max_length=10)),
                ('log_repair', models.CharField(max_length=200, null=True)),
                ('log_time', models.DateTimeField(max_length=30, null=True)),
                ('log_device', models.ForeignKey(db_column='log_device', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='One.device')),
                ('log_project', models.ForeignKey(db_column='log_project', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='One.project')),
            ],
        ),
    ]
