# Generated by Django 3.1.2 on 2021-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0091_alarmlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_status',
            field=models.IntegerField(default=0),
        ),
    ]
