# Generated by Django 3.1.2 on 2021-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0092_auto_20210206_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='k_status',
            field=models.CharField(default='未审核', max_length=10),
        ),
    ]
