# Generated by Django 3.1.2 on 2021-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0093_auto_20210206_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='a_high_level',
            field=models.CharField(default='预警', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_highest_level',
            field=models.CharField(default='告警', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_low_level',
            field=models.CharField(default='预警', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_lowest_level',
            field=models.CharField(default='告警', max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='k_status',
            field=models.IntegerField(default=0),
        ),
    ]
