# Generated by Django 3.1.2 on 2021-02-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0094_auto_20210206_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='a_c_id',
            field=models.ForeignKey(db_column='a_c_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.collectdevice'),
        ),
        migrations.AddField(
            model_name='alert',
            name='a_company_id',
            field=models.ForeignKey(db_column='a_company_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.company'),
        ),
        migrations.AddField(
            model_name='alert',
            name='a_device_id',
            field=models.ForeignKey(db_column='a_device_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='a_project_id',
            field=models.ForeignKey(db_column='a_project_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.project'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='a_datagroup_id',
            field=models.ForeignKey(db_column='a_datagroup_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.datagroup'),
        ),
    ]
