# Generated by Django 3.1.2 on 2021-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0095_auto_20210206_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='company_number',
            field=models.IntegerField(null=True),
        ),
    ]
