# Generated by Django 3.1.2 on 2021-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0096_loginuser_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='d_company_number',
            field=models.IntegerField(null=True),
        ),
    ]
