# Generated by Django 3.1.2 on 2021-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0097_device_d_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='draft',
            field=models.BooleanField(default=0),
        ),
    ]
