# Generated by Django 3.1.2 on 2021-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0098_company_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='k_draft',
            field=models.BooleanField(default=0),
        ),
    ]
