# Generated by Django 3.1.2 on 2021-02-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0099_knowledge_k_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmlog',
            name='log_company',
            field=models.ForeignKey(db_column='log_company', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='One.company'),
        ),
    ]
