# Generated by Django 3.1.2 on 2021-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0101_datagroup_alert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='w_u_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
