# Generated by Django 3.1.2 on 2021-02-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0102_auto_20210207_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataLog',
            new_name='DataLogJan2021',
        ),
    ]
