# Generated by Django 3.1.2 on 2021-02-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0103_auto_20210222_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogjan2021',
            name='dl_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='datalogjan2021',
            name='dl_g_id',
            field=models.ForeignKey(db_column='dl_g_id_jan', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.datagroup'),
        ),
        migrations.CreateModel(
            name='DataLogMar2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_value', models.CharField(max_length=50, null=True)),
                ('dl_time', models.DateTimeField(null=True)),
                ('dl_month', models.IntegerField(default=2)),
                ('dl_g_id', models.ForeignKey(db_column='dl_g_id_mar', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.datagroup')),
            ],
        ),
        migrations.CreateModel(
            name='DataLogFeb2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_value', models.CharField(max_length=50, null=True)),
                ('dl_time', models.DateTimeField(null=True)),
                ('dl_month', models.IntegerField(default=2)),
                ('dl_g_id', models.ForeignKey(db_column='dl_g_id_feb', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='One.datagroup')),
            ],
        ),
    ]
