# Generated by Django 3.1.2 on 2021-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0104_auto_20210222_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('company', models.CharField(max_length=40, null=True)),
                ('contactnumber', models.CharField(max_length=40, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
