# Generated by Django 3.1.2 on 2021-02-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0105_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='read',
            field=models.BooleanField(default=0),
        ),
    ]
