# Generated by Django 3.1.2 on 2021-02-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0106_contactus_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
