# Generated by Django 3.1.2 on 2021-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0108_datalogapr2021_datalogaug2021_datalogdec2021_datalogjul2021_datalogjun2021_datalogmay2021_datalognov'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagroup',
            name='dg_type',
            field=models.CharField(default='其他', max_length=32),
        ),
    ]
