# Generated by Django 3.1.2 on 2021-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0109_datagroup_dg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='openid',
            field=models.CharField(max_length=30, null=True, verbose_name='微信OpenId'),
        ),
    ]
