# Generated by Django 3.1.2 on 2021-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('One', '0110_loginuser_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogapr2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogaug2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogdec2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogfeb2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogjan2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogjul2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogjun2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogmar2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogmay2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalognov2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogoct2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datalogsep2021',
            name='dl_d_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='openid',
            field=models.CharField(max_length=100, null=True, verbose_name='微信OpenId'),
        ),
    ]
