# Generated by Django 3.1.1 on 2020-09-18 14:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sBlog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
