# Generated by Django 3.1.1 on 2020-09-21 08:47

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('text', '0002_auto_20200918_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sBlog',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='a default title', max_length=64)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('personal_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
